POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "username": "ferds",
  "password": "ABCdef123!!!"
}
###
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "username": "ferds",
  "password": "ABCdef123!!!"
}
###
GET http://localhost:3000/tasks
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZlcmRzIiwiaWF0IjoxNjIwNDk2Mjg3LCJleHAiOjE2MjA0OTk4ODd9.Mq6FfcwouPmZ1OVAI0r_c9I2H5uFPSVIxW6ZVihoQv4
###

POST http://localhost:3000/tasks
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZlcmRzIiwiaWF0IjoxNjIwNDk2Mjg3LCJleHAiOjE2MjA0OTk4ODd9.Mq6FfcwouPmZ1OVAI0r_c9I2H5uFPSVIxW6ZVihoQv4
Content-Type: application/json

{
  "title": "Test",
  "description": "lala"
}